// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8e83a6c1-0a33-4657-b7e4-6bb9c333981a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ILVi57O70",
    "aws_user_pools_web_client_id": "c2a5tgogssun954l4dqgg362b",
    "aws_content_delivery_bucket": "wingman-elevate",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://wingman-elevate.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
